version: "3.9"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      API_PORT: "${API_PORT}"
      SECRET_KEY: /run/secrets/api_secret
    secrets:
      - api_secret
    volumes:
      - ./api/src:/app/src
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
      args:
        API_URL: "http://api:${API_PORT}"
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      API_URL: "http://api:${API_PORT}"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules

secrets:
  api_secret:
    file: api-secret.txt
