version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.prod
      args:
        API_PORT: ${API_PORT}
        POETRY_VERSION: ${POETRY_VERSION}
        MAILCTL_VERSION: ${MAILCTL_VERSION}
        MSMTP_VERSION: ${MSMTP_VERSION}
        MAILCTL_SERVICES: ${MAILCTL_SERVICES}
        MAILCTL_ACCOUNT: ${MAILCTL_ACCOUNT}
        KEY_ID: ${KEY_ID}
        PRIVATE_KEY: /run/secrets/gpg_private
        MSMTP_HOST: ${MSMTP_HOST}
        MSMTP_PORT: ${MSMTP_PORT}
        MSMTP_AUTH: ${MSMTP_AUTH}
        MSMTP_FROM: ${MSMTP_FROM}
        MSMTP_USER: ${MSMTP_USER}
        MSMTP_EVAL: ${MSMTP_EVAL}
      secrets:
        - gpg_private
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    environment:
      API_PORT: "${API_PORT}"
      SECRET_KEY: /run/secrets/api_secret
      MAILCTL_TOKEN: ${MAILCTL_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cookies_api.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.cookies_api.tls=true"
      - "traefik.http.routers.cookies_api.tls.certresolver=lets-encrypt"
      - "traefik.http.services.cookies_api.loadbalancer.server.port=${API_PORT}"
    networks:
      - internal
      - web
    secrets:
      - api_secret
      - gpg_private
    volumes:
      - ${MAILCTL_TOKEN}:/app/mail/token.auth
  client:
    build:
      context: client
      dockerfile: Dockerfile.prod
      args:
        CLIENT_PORT: ${CLIENT_PORT}
        API_URL: "http://api:${API_PORT}"
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      API_URL: "http://api:${API_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cookies_client.rule=Host(`${CLIENT_HOST}`)"
      - "traefik.http.routers.cookies_client.tls=true"
      - "traefik.http.routers.cookies_client.tls.certresolver=lets-encrypt"
      - "traefik.http.services.cookies_client.loadbalancer.server.port=${CLIENT_PORT}"
    networks:
      - internal
      - web
    depends_on:
      - api

secrets:
  api_secret:
    file: api-secret.txt
  gpg_private:
    file: ${GPG_SECRET_KEY}
