networks:
  internal:
    external: false
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cookies
      POSTGRES_DB: cookies
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    secrets:
      - db_password
    networks:
      - internal
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
      args:
        API_PORT: ${API_PORT}
        POETRY_VERSION: ${POETRY_VERSION}
        MAILCTL_VERSION: ${MAILCTL_VERSION}
        MSMTP_VERSION: ${MSMTP_VERSION}
        MAILCTL_SERVICES: ${MAILCTL_SERVICES}
        MAILCTL_ACCOUNT: ${MAILCTL_ACCOUNT}
        KEY_ID: ${KEY_ID}
        PRIVATE_KEY: /run/secrets/gpg_private
        MSMTP_HOST: ${MSMTP_HOST}
        MSMTP_PORT: ${MSMTP_PORT}
        MSMTP_AUTH: ${MSMTP_AUTH}
        MSMTP_FROM: ${MSMTP_FROM}
        MSMTP_USER: ${MSMTP_USER}
        MSMTP_EVAL: ${MSMTP_EVAL}
      secrets:
        - gpg_private
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      API_PORT: "${API_PORT}"
      SECRET_KEY: /run/secrets/api_secret
      MAILCTL_TOKEN: ${MAILCTL_TOKEN}
      DB_HOST: db
      DB_USER: cookies
      DB_NAME: cookies
      DB_PASSWORD: /run/secrets/db_password
    secrets:
      - api_secret
      - gpg_private
    volumes:
      - ./api/src:/app/src
      - ${MAILCTL_TOKEN}:/app/mail/token.auth
    networks:
      - internal
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
      args:
        CLIENT_PORT: ${CLIENT_PORT}
        API_URL: "http://api:${API_PORT}"
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      API_URL: "http://api:${API_PORT}"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    networks:
      - internal
  updater:
    build:
      context: updater
      dockerfile: Dockerfile
      args:
        CRON: "* * * * *"
        POETRY_VERSION: ${POETRY_VERSION}
    environment:
      API_USER: ${API_USER}
      API_PASSWORD: /run/secrets/api_password
      API_ENDPOINT: "http://api:${API_PORT}"
    depends_on:
      - api
    secrets:
      - api_password
    networks:
      - internal
secrets:
  api_secret:
    file: ${API_SECRET_FILE}
  gpg_private:
    file: ${GPG_SECRET_KEY_FILE}
  api_password:
    file: ${API_PASSWORD_FILE}
  db_password:
    file: ${DB_PASSWORD_FILE}