FROM python:3.11-bookworm

RUN apt update
RUN apt install cron -y

ARG POETRY_VERSION=1.5.1
ARG CRON="* * * * *"

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache \
    VIRTUAL_ENV=/app/.venv \
    PATH=/app/.venv/vin:$PATH \
    PYTHONPATH=/app/src:$PYTHONPATH

RUN pip install poetry==${POETRY_VERSION}

WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN touch README.md
RUN poetry install --no-root

COPY src ./src
RUN poetry install

RUN mkdir /run/secrets
RUN echo password > /run/secrets/api_password
RUN echo password > /run/secrets/db_password
RUN echo "${CRON} cd /app && /usr/local/bin/poetry run python /app/src/updater/main.py > /tmp/stdout 2> /tmp/stderr" > crontab
RUN crontab crontab

COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

CMD [ "./entrypoint.sh" ]

